// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LottoMonteCarlo")>]
[<assembly: AssemblyProductAttribute("RandomBits")>]
[<assembly: AssemblyDescriptionAttribute("Random bits from ANU.")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LottoMonteCarlo"
    let [<Literal>] AssemblyProduct = "RandomBits"
    let [<Literal>] AssemblyDescription = "Random bits from ANU."
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
    let [<Literal>] AssemblyConfiguration = "Release"
